version: "3.9"

services:
  redis:
    image: redis:7-alpine 
    container_name: redis
    restart: always
    ports:
      - "6379:6379"  
    networks:
      - app-network

  test-app:
    image: joelgallan/test-app:latest
    container_name: test-app
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
