name: Build and Push Go Docker Image

on:
  push:
    branches:
      - main   # Trigger on pushes to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build Docker image
    - name: Build Docker image
      run: docker build -t joelgallan/test-app:latest .

    # 4. Push to Docker Hub
    - name: Push Docker image
      run: docker push joelgallan/test-app:latest

    # 5. Deploy via SSH
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          mkdir -p ~/apps/test-app

    # 4.5 Upload docker-compose.yaml to VPS
    - name: Upload docker-compose.yaml to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "docker-compose.yaml"
        target: "~/apps/test-app/"

    # 5. Deploy via SSH
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/apps/test-app
          docker compose pull
          docker compose up -d
          docker system prune -af --volumes



